global:
  security:
    allowInsecureImages: true

replicaCount: 1

service:
  type: ClusterIP
  port: 80

image:
  registry: docker.io
  repository: techino/nginix
  tag: "10.0"
  pullPolicy: Always
